### ISSUE TITLE
Pick a member of the team to make the tea

### ISSUE THREAD

**Issue by dingjimmy** [dingjimmy/TeaRoundPicker#1]
### User Story

As a team
We want one member to be picked to make tea for others who participate
So that we do not have to spend time deciding who should do it.

### Acceptance Criteria

Given the team is ready for another round of tea
When the tool is started
Then user is prompted to add the name of participants

Given the names of all participants has been entered
When user confirms this
Then the tool picks one of the names and displays it to the user

### Tasks
- [x] Design 
- [x] Implement core logic
- [x] Create tests for core logic
- [ ] #6
- [x] Host in console app

### Design
[Domain Model](https://github.com/dingjimmy/TeaRoundPicker/wiki/The-Model) _(This is a living doc, so may have changes from last time you saw it)_
