### ISSUE TITLE
Pick a member from smartphones, tablets and laptops

### ISSUE THREAD

**Issue by dingjimmy** [dingjimmy/TeaRoundPicker#2]
**User Story:**

As a team
We want to access the tea picker from smartphones, tablets and laptops
So that we can access it conveniently where ever we are, with what ever device we have to hand; i.e. we are not be tied to our laptops!

**Acceptance Criteria:**

Given the team is ready for another round of tea
When user enter the URL into a browser
Then they are presented with the Tea Round Picker web app

**Tasks**

- [ ] Convert to web app project
- [ ] Create UI
- [ ] Create Tests
- [ ] Source a hosting environment
- [ ] Create CI/CD pipeline
